prepare-mongodb.md

DOC PR: https://github.com/ajktown/docs/pull/3
FE PR: https://github.com/ajktown/wordnote/pull/20
API PR: https://github.com/ajktown/api/pull/3

Local connection test between Local Mongo DB, API and FE

---

api/source-directories.md
prepare-envoy.md

Doc: https://github.com/ajktown/docs/pull/5
FE: https://github.com/ajktown/wordnote/pull/22
API: https://github.com/ajktown/api/pull/5

Get words by params

---

code_writing_conventions/recoil-state.md
commits_naming.md

Docs: https://github.com/ajktown/docs/pull/6
FE: https://github.com/ajktown/wordnote/pull/24

Refactor recoil state docs

---

api/api-errors.md
fe/sign-out-hooks.md
fe/sign-out.md

Doc: https://github.com/ajktown/docs/pull/8
FE: https://github.com/ajktown/wordnote/pull/29
API: https://github.com/ajktown/api/pull/11

Sign out Feature

---

api/api-errors.md

Update on the doc for the changes on https://github.com/ajktown/api/pull/41

Nest js Defined Exceptions are thrown with standardized messages

---

eksctl/01_setup.md

The price of eks per month with details

Price Details Documentation 

---

eksctl/05_create-secret.md

The current document misleads by missing `-n`
- At least one or more issue is linked to this PR
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](#issue) above, if no issue is related to this PR

Doc Fixed For Decode

---

code_writing_conventions/react.md

Documentation for New Suffix `Part` introduced on https://github.com/ajktown/wordnote/pull/87 
- https://github.com/ajktown/wordnote/issues/89
- https://github.com/ajktown/docs/pull/21
- https://github.com/ajktown/api/pull/56
- https://github.com/ajktown/wordnote/pull/87
- At least one or more issue is linked to this PR
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](#issue) above, if no issue is related to this PR

Link for Example

---

api/api-src-directories.md

The documentation for `factory` should be improved
- _None_
- At least one or more issue are linked to this PR under `development`
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) is directly copied above the `Related PRs`

Doc for Factory

---

api/add-new-field.md
api/add-new-filled.md
api/domain-driven-design.md
code_writing_conventions/react-hooks.md
prepare-envoy.md

- https://github.com/ajktown/docs/pull/25
- https://github.com/ajktown/wordnote/issues/105
- https://github.com/ajktown/api/pull/63
- At least one or more issue are linked to this PR under `development`
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) is directly copied above the `Related PRs`
- One of the related PRs is linked to the issue under `development`

Docs Archive feature for word

---

dev/diagrams/on-click-refresh-button.md

- _None_
- At least one or more issue are linked to this PR under `development`
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) is directly copied above the `Related PRs`
- You can directly copy background with issue from the samed/different repository.
- One of the related PRs is linked to the issue under `development`

Doc click refresh flow changed

---

dev/diagrams/auth-flow.md

(https://github.com/ajktown/docs/issues/44)

Doc Auth Flow with Color

---

dev/diagrams/on-dev-token-sign-in-handlers.md

https://github.com/ajktown/docs/issues/42

Doc onDevTokenSignInHandlers

---

dev/diagrams/on-post-word-with-string-hook.md
install/eks_eksctl/01_setup.md

(https://github.com/ajktown/docs/issues/46)

No Tab in Docs

---

dev/diagrams/on-app-booting-hook.md

Doc onAppBooting

---

dev/diagrams/on-click-post-word-from-undo.md

https://github.com/ajktown/docs/issues/53
`

Doc for Modified Undo Function Doc

---

dev/git/commit-name-prefix.md

When you rename certain variables or file name to refactor code, we realize it is better to distinguish between `refactor` and `rename

New Commit Name Action

---

dev/writing_conventions/fe/passing-callbacks.md

Passing callback rules are defined
Please copy and paste the following into your review, ensuring each checkbox is marked as checked
```
```

Passing Callback Convention

---

install/vs_code_extensions/install-ajktown-recommended-extensions.md

- The extension we have been using  is not good. We have to recommend another TOC extension.
Please copy and paste the following into your review, ensuring each checkbox is marked as checked
```
```

Change Extension of TOC

---

install/vs_code_extensions/install-ajktown-recommended-extensions.md

https://github.com/ajktown/docs/issues/64

Add Code Spell Checking extension Code Spell Checker

---

install/chrome_extensions/install-ajktown-recommmended-chrome-extensions.md

https://github.com/ajktown/docs/issues/72

Chrome Extension Documented

---

install/ec2_k3s/10_ingress.yaml
install/eks_eksctl/04_ingress.yaml

ConsistencyGPT is released in Feb 11, 2024 through the PR https://github.com/ajktown/ConsistencyGPT/pull/5
It now requires a new ingress yaml file to direct to the new service `ajktown-consistency-svc`

New ingress consistency.ajktown.com

---

install/plantuml/install-plantuml.md
install/plantuml/use-remote-plantuml-server.md

https://github.com/ajktown/docs/issues/58

Plantuml Splitted

---

dev_consistency/diagrams/on-get-action-groups.md
dev_consistency/diagrams/on-post-action-group.md
dev_consistency/diagrams/on-post-action.md
dev_consistency/index.md

The API returns ActionGroupsDomain for daily post word challenge in the PR https://github.com/ajktown/api/pull/77.
Yet the changes made in the PR https://github.com/ajktown/api/pull/77 was just for the posting word and we would like to standarize how to handle action, action group in the future. 
At this point ActionDomain and ActionGroupDomain will never be deleted/updated to make the app even more trustworhty.
Please copy and paste the following into your review, ensuring each checkbox is marked as checked
```
```

Docs for Post and Get for new domain ACTION

---

README.md

I, as a developer myself also realize that the technical writing is extremely important especially for your professional work. AJK Town wants to standardise reading technical writing course that Google provides to make this repository concise.
https://developers.google.com/tech-writing/overview

Google Technical Writing Recommendation for AJK Town Docs to be well formatted and documented

---

dev_consistency/README.md
dev_consistency/diagrams/README.md
dev_consistency/writing_conventions/README.md

https://github.com/ajktown/docs/issues/88

Implement simple README.md files under dev_consistency

---

README.md

Google has amazing, well-organized documentation format for themselves.
https://developers.google.com/style
AJK Town should do the same to follow the world-leading standard.

Google developer documentation style guide

---

install/vs_code_extensions/install-ajktown-recommended-extensions.md

https://github.com/ajktown/ConsistencyGPT/issues/29

Mermaid Tools

---

dev_api/domains/action-group.md

Action Group Level Decision Doc

---

dev_consistency/diagrams/on-get-rituals-first-time.md
dev_consistency/diagrams/on-get-rituals.md

Sequence diagram for GET /api/v1/rituals for the first time user of ConsistencyGPT

Doc Get Ritual For The First Time

---

dev_consistency/diagrams/on-get-rituals.md

Explain how `GET /api/v1/rituals` does the following:
- Get requester's rituals from the database
- Get requester's action groups from the data
- Map action groups to correct rituals
- Order action groups based on user's setting
- Return the response

updated doc `GET /api/v1/rituals`

---

dev_api/diagrams/get-words.md

Document basic `GET /api/v1/words`

Document basic `GET /api/v1/words`

---

dev_api/domains/action-group.md

Write every possibility of action group state

Document available states for Action Group Domain

---

.vscode/settings.json
dev_api/diagrams/get-rituals.md
dev_api/diagrams/patch-ritual-by-default.md
dev_api/diagrams/post-archived-action-group.md
dev_api/domains/archive.md
dev_api/domains/ritual-group.md
dev_api/writing_conventions/domain-driven-design.md
dev_consistency/diagrams/on-get-rituals-by-nickname.md
dev_consistency/diagrams/on-get-rituals.md

Document architecture for achieve feature for action groups

Archive feature for Action Groups under Ritual

---

dev_api/diagrams/post-word.md

Write a diagram for `POST /api/v1/words`

Document post word diagram with recent tags

---

README.md

Small indent

---

dev_api/diagrams/patch-word-by-id.md

Patch Word Documented for API

---

install/ec2_k3s/10_ingress.yaml
install/eks_eksctl/04_ingress.yaml

new application golf - ajktown has been released as the following: 
New ingress setting is required

New Ingress for golf

---

dev_general/logos/obtain-ajktown-logo.md

Documentation for how to create a logo for the new domain golf.ajktown.com

Golf new logo

---

install/trivy/index.md

AJK Town has found a great image vulnerability scanner application

Document how to install trivy

---

dev_api/diagrams/get-action-group-by-id.md

`GET /api/v1/action-groups/{id}`

Document `GET /api/v1/action-groups/{id}`

---

dev_api/domains/action-group.md

I was not able to understand what `DummyCommitted` really means so I added the explanation.

Doc: `Committed`, `DummyCommitted`, `NotCommitted`

---

.vscode/settings.json
dev_api/domains/index.hierarchy.md

Domains are not created equal. Some domains manage other domains. But the problem is that every domain is handled under the same directory `/src/domains` - which is hard to understand who is controlling what. We now have a goal to clarify the hierarchy of domains in the API server. After seeing the hierarchy, you can understand the relationship between domains and how they are managed. Also you will see the naming convention for each domain.
Created the following hierarchy diagram:
I've learned them some of the parent domains have two suffixes:
- Chunk
- Group
And wanna fix this inconsistency later in the future. For now the `group` sounds better as the word `chunk` is used in FE & less direct.
**Issue created: https://github.com/ajktown/api/issues/162**
Also learned that the following …

Doc: domain hierarchy

---

dev_api/domains/index.hierarchy.md

I've made naming changes in the following PR: https://github.com/ajktown/api/pull/164. Now I want to make sure the documentation is well synced.
As-is:
To-be:
*Minor fixes done, including some typo fixes, DomainRoot => RootDomain*
Synced with the changes: https://github.com/ajktown/api/pull/164
None
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- `Draft` is set for this PR
- `Development` is linked if related issue exists
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Review Code
- `Checklist Before PR Review` is correctly …

Doc: Domain Hierarchy Synced

---

dev_api/README.md

https://github.com/ajktown/docs/issues/89
Write doc `README.md` for `dev_api`
- https://github.com/ajktown/docs/pull/87
- TODO: What is the next things to do after this PR is merged?
- TODO: Not sure how to do it? Use the following PR as a reference: https://github.com/ajktown/docs/pull/115
- TODO: If you think you have none, you can simply leave `None` or `N/A`
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- `Draft` is set for this PR
- `Development` is linked if related issue exists
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual …

Doc: dev_api with `README.md`
